# Generated by Django 4.2.3 on 2023-07-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(blank=True, max_length=50)),
                ('gmail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_modify', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
