# Generated by Django 4.2.2 on 2023-08-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_avatar_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/products/', verbose_name='avatar'),
        ),
    ]
